// Buscar usuário no banco de dados por email
GET http://localhost:8000/getUserByEmail/test@gmail.com
Accept: application/json
Authorization:
###

// Buscar usuário no banco de dados por email
GET http://localhost:8000/getUserById/65950f472641fdcc7bdb0dd3
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIwLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzA0Mzk1MzkwLCJpZCI6IjY1OTUwZjQ3MjY0MWZkY2M3YmRiMGRkMyIsIm5hbWUiOiJUZXN0In0.f1qXCdIzldm71rmP7IiLNrrNA6aR-OgbTXjQaylKvZ4
###

// Criar um usuario dentro do banco de dados
POST http://localhost:8000/createUser
Content-Type: application/json

{
  "email": "test@gmail.com",
  "age": 20,
  "password": "test#!@!dwdw",
  "name": "Test"
}
###

// Atualiza um usuario já criado dentro do banco de dados
PUT http://localhost:8000/updateUser/65950f472641fdcc7bdb0dd3
Content-Type: application/json

{
  "email": "another_test@test.com",
  "age": 90
}
###

// Apaga um usuário do banco de dados dado um userId
DELETE http://localhost:8000/deleteUser/6423852a15cd25e0b80f8535
Accept: application/json
###

// Realiza o login do usuário com email e senha
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test#!@!dwdw"
}
###